"""Update Restaurant and Review models

Revision ID: 47dce06c086f
Revises: 3fe432c99deb
Create Date: 2025-01-15 14:16:06.137934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '47dce06c086f'
down_revision: Union[str, None] = '3fe432c99deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visits_id', table_name='visits')
    op.drop_table('visits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visits',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('restaurant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('visit_date', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name='visits_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='visits_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_visits_id', 'visits', ['id'], unique=False)
    # ### end Alembic commands ###
